service: causef-api-v2-subscribers

frameworkVersion: "3"

plugins:
  - serverless-domain-manager
custom:
  environment: ${file(../.env.${sls:stage}.yml)}
  customDomain:
    enabled: ${param:customDomainEnabled, true}
    domainName: ${self:custom.environment.CUSTOM_DOMAIN}
    basePath: subscription
    stage: ${sls:stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${sls:stage}
  region: ${self:custom.environment.AWS_ACCOUNT_REGION}
  environment: ${file(../.env.${sls:stage}.yml)}
  apiGateway:
    description: Microservice for subscriber specific processes
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendRawEmail"
      Resource:
        - arn:aws:ses:eu-west-1:988218197909:identity/jamiebuckell.co.uk
        - arn:aws:ses:eu-west-1:988218197909:identity/cause-foundation.org.uk
        - arn:aws:ses:eu-west-1:988218197909:configuration-set/cause-failure-configuration
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.SUBSCRIBERS_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.EMAIL_TEMPLATES_TABLE}
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  create:
    handler: endpoints/create.handler
    events:
      - http:
          method: post
          path: create
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  delete:
    handler: endpoints/delete.handler
    events:
      - http:
          method: post
          path: delete/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
  subscribe:
    handler: endpoints/subscribe.handler
    events:
      - http:
          method: post
          path: subscribe
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:uuid:1
  verification:
    handler: endpoints/verification.handler
    events:
      - http:
          method: get
          path: verify/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  list:
    handler: endpoints/list.handler
    events:
      - http:
          method: get
          path: list
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  check:
    handler: endpoints/check.handler
    events:
      - http:
          method: get
          path: check/{emailAddress}/{hash}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
                hash: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  unsubscribe:
    handler: endpoints/unsubscribe.handler
    events:
      - http:
          method: get
          path: unsubscribe/{emailAddress}/{hash}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
                hash: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  resubscribe:
    handler: endpoints/resubscribe.handler
    events:
      - http:
          method: get
          path: resubscribe/{emailAddress}/{hash}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
                hash: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
resources:
  - ${file(../resources/subscribers-table.yml)}
  - ${file(../resources/api-gateway-responses.yml)}
