Resources:
  EmailsSubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.EMAILS_SUBSCRIBERS_TABLE}
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
        - AttributeName: emailId
          AttributeType: S
        - AttributeName: subscriberId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailRequest
          KeySchema:
            - AttributeName: emailId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: subscriberRequest
          KeySchema:
            - AttributeName: subscriberId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      BillingMode: PROVISIONED