service: causef-api-v2-campaigns

useDotenv: true
frameworkVersion: "4"

plugins:
  - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  userPools:
    dev: "arn:aws:cognito-idp:eu-west-2:988218197909:userpool/eu-west-2_Tq53Gr5Pd"
    live: "arn:aws:cognito-idp:eu-west-2:988218197909:userpool/eu-west-2_ueeqpE5iq"
  domains:
    live: api.cause-foundation.org.uk
    dev: causeapi.bouchelle.co.uk
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: campaigns
    stage: ${self:provider.stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs16.x
  profile: jamiebuckell
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  environment: ${file(../resources/.env.${self:custom.stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.SUBSCRIBERS_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.EMAIL_TEMPLATES_TABLE}
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  create:
    handler: endpoints/create.handler
    events:
      - http:
          method: post
          path: create
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  list:
    handler: endpoints/list.handler
    events:
      - http:
          method: get
          path: list
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
  getById:
    handler: endpoints/getById.handler
    events:
      - http:
          method: get
          path: get-by-id/{campaignId}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
  update:
    handler: endpoints/update.handler
    events:
      - http:
          method: post
          path: update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  delete:
    handler: endpoints/delete.handler
    events:
      - http:
          method: post
          path: delete/{campaignId}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  verify:
    handler: endpoints/verify.handler
    events:
      - http:
          method: get
          path: verify
          cors: true
          integration: lambda-proxy
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  dashboard:
    handler: endpoints/dashboard.handler
    events:
      - http:
          method: get
          path: dashboard/{campaignId}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
resources:
  - ${file(../resources/portal-data-store.yml)}
  - ${file(../resources/api-gateway-responses.yml)}
