service: causef-api-v2-communications

useDotenv: true
frameworkVersion: "4"

plugins:
  - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  userPools:
    dev: "arn:aws:cognito-idp:eu-west-2:988218197909:userpool/eu-west-2_Tq53Gr5Pd"
    live: "arn:aws:cognito-idp:eu-west-2:988218197909:userpool/eu-west-2_ueeqpE5iq"
  domains:
    live: api.cause-foundation.org.uk
    dev: causeapi.bouchelle.co.uk
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: communications
    stage: ${self:provider.stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs16.x
  profile: jamiebuckell
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  apiGateway:
    description: Microservice for communication specific processes
  environment: ${file(../resources/.env.${self:custom.stage}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendRawEmail"
      Resource:
        - arn:aws:ses:eu-west-1:988218197909:identity/jamiebuckell.co.uk
        - arn:aws:ses:eu-west-1:988218197909:identity/cause-foundation.org.uk
        - arn:aws:ses:eu-west-1:988218197909:configuration-set/cause-failure-configuration
    - Effect: Allow
      Action:
        - sqs:sendmessage
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:sqs:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":"
              - ${self:provider.environment.MAIL_PROCESSOR_QUEUE}
        - Fn::Join:
            - ""
            - - "arn:aws:sqs:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":"
              - ${self:provider.environment.MAILER_QUEUE}
        - Fn::Join:
            - ""
            - - "arn:aws:sqs:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":"
              - ${self:provider.environment.MAIL_COMPLETE_QUEUE}
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.COMMS_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.SUBSCRIBERS_TABLE}
    - Effect: Allow
      Action:
        - "ses:GetTemplate"
      Resource:
        - "*"
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  processEmail:
    handler: endpoints/process.handler
    events:
      - http:
          method: post
          path: process
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  generateMails:
    handler: endpoints/generate.handler
    timeout: 60
    reservedConcurrency: 10
    events:
      - sqs:
          batchSize: 50
          maximumBatchingWindow: 1
          arn:
            Fn::GetAtt:
              - MailProcessorQueue
              - Arn
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  sendEmails:
    handler: endpoints/mailer.handler
    timeout: 120
    reservedConcurrency: 10
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt:
              - MailerQueue
              - Arn
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  completeSend:
    handler: endpoints/complete.handler
    timeout: 120
    reservedConcurrency: 10
    events:
      - sqs:
          batchSize: 50
          maximumBatchingWindow: 1
          arn:
            Fn::GetAtt:
              - MailerCompleteQueue
              - Arn
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  sent:
    handler: endpoints/sent.handler
    events:
      - http:
          method: get
          path: sent
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
resources:
  - ${file(../resources/portal-comms-data-store.yml)}
  - ${file(../resources/mail-processor-sqs-queue.yml)}
  - ${file(../resources/mailer-sqs-queue.yml)}
  - ${file(../resources/mailer-complete-sqs-queue.yml)}
  - ${file(../resources/api-gateway-responses.yml)}
