service: sharp-layer

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  profile: jamiebuckell

layers:
  Moment:
    path: nodejs
    description: Includes the Sharp node_module package
    compatibleRuntimes:
      - nodejs14.x
      - nodejs16.x