service: causef-api-v2-donors

frameworkVersion: "3"

plugins:
  - serverless-domain-manager
custom:
  environment: ${file(../.env.${sls:stage}.yml)}
  customDomain:
    domainName: ${self:custom.environment.CUSTOM_DOMAIN}
    basePath: donors
    stage: ${sls:stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${sls:stage}
  region: ${self:custom.environment.AWS_ACCOUNT_REGION}
  environment: ${file(../.env.${sls:stage}.yml)}
  apiGateway:
    description: Microservice for donor specific processes
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendRawEmail"
      Resource:
        - arn:aws:ses:eu-west-1:988218197909:identity/jamiebuckell.co.uk
        - arn:aws:ses:eu-west-1:988218197909:identity/cause-foundation.org.uk
        - arn:aws:ses:eu-west-1:988218197909:configuration-set/cause-failure-configuration
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI1"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.SUBSCRIBERS_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.EMAIL_TEMPLATES_TABLE}
    - Effect: Allow
      Action:
        - sqs:sendmessage
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:sqs:"
              - ${self:provider.region}
              - ":"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":"
              - ${self:custom.environment.PLEDGE_DETAIL_QUEUE}
    - Effect: Allow
      Action:
        - "ses:GetTemplate"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:eu-west-2:988218197909:function:PdfGeneratorV2Stack-HtmlToPdfLambdaB7443488-LJXTgl6nvBE2
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - arn:aws:s3:::pdfgeneratorv2stack-pdfss3bucketddbbf369-c95xtwuskgpv/*
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  register:
    handler: endpoints/register.handler
    events:
      - http:
          method: post
          path: register
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  delete:
    handler: endpoints/delete.handler
    events:
      - http:
          method: post
          path: delete
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  hide:
    handler: endpoints/hide.handler
    events:
      - http:
          method: post
          path: hide
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
  emailUpdate:
    handler: endpoints/emailUpdate.handler
    events:
      - http:
          method: post
          path: email-update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  updatePledge:
    handler: endpoints/updatePledge.handler
    events:
      - http:
          method: post
          path: update-pledge
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  update:
    handler: endpoints/update.handler
    events:
      - http:
          method: post
          path: update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  resendVerification:
    handler: endpoints/resendVerification.handler
    events:
      - http:
          method: post
          path: resend-verification
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  confirmPledge:
    handler: endpoints/confirmPledge.handler
    events:
      - http:
          method: post
          path: confirm-pledge/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
      - http:
          method: get
          path: confirm-pledge/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
  changePledge:
    handler: endpoints/changePledge.handler
    events:
      - http:
          method: post
          path: change-pledge/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  sendPledgeDetail:
    handler: endpoints/sendPledgeDetail.handler
    timeout: 12
    reservedConcurrency: 10
    events:
      - sqs:
          batchSize: 50
          maximumBatchingWindow: 1
          arn:
            Fn::GetAtt:
              - SendPledgeDetailQueue
              - Arn
  downloadFile:
    handler: endpoints/downloadFile.handler
    timeout: 30
    events:
      - http:
          method: post
          path: download-file
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
resources:
  - ${file(../resources/send-pledge-sqs-queue.yml)}
  - ${file(../resources/api-gateway-responses.yml)}
