service: causef-api-v2-donors

useDotenv: true
frameworkVersion: "4"

plugins:
  - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  userPools:
    dev: "arn:aws:cognito-idp:eu-west-2:988218197909:userpool/eu-west-2_Tq53Gr5Pd"
    live: "arn:aws:cognito-idp:eu-west-2:988218197909:userpool/eu-west-2_ueeqpE5iq"
  domains:
    live: api.cause-foundation.org.uk
    dev: causeapi.bouchelle.co.uk
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: donors
    stage: ${self:provider.stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs14.x
  profile: jamiebuckell
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  apiGateway:
    description: Microservice for donor specific processes
  environment: ${file(../resources/.env.${self:custom.stage}.yml):}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendRawEmail"
      Resource:
        - arn:aws:ses:eu-west-1:988218197909:identity/jamiebuckell.co.uk
        - arn:aws:ses:eu-west-1:988218197909:identity/cause-foundation.org.uk
        - arn:aws:ses:eu-west-1:988218197909:configuration-set/cause-failure-configuration
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI1"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.SUBSCRIBERS_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:provider.environment.EMAIL_TEMPLATES_TABLE}
    - Effect: Allow
      Action:
        - sqs:sendmessage
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:sqs:"
              - ${self:provider.region}
              - ":"
              - ${self:provider.environment.AWS_ACCOUNT_ID}
              - ":"
              - ${self:provider.environment.PLEDGE_DETAIL_QUEUE}
    - Effect: Allow
      Action:
        - "ses:GetTemplate"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:eu-west-2:988218197909:function:pdf-live-downloadPdf
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  register:
    handler: endpoints/register.handler
    events:
      - http:
          method: post
          path: register
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  delete:
    handler: endpoints/delete.handler
    events:
      - http:
          method: post
          path: delete
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
  emailUpdate:
    handler: endpoints/emailUpdate.handler
    events:
      - http:
          method: post
          path: email-update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  updatePledge:
    handler: endpoints/updatePledge.handler
    events:
      - http:
          method: post
          path: update-pledge
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  update:
    handler: endpoints/update.handler
    events:
      - http:
          method: post
          path: update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  resendVerification:
    handler: endpoints/resendVerification.handler
    events:
      - http:
          method: post
          path: resend-verification
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  confirmPledge:
    handler: endpoints/confirmPledge.handler
    events:
      - http:
          method: post
          path: confirm-pledge/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
      - http:
          method: get
          path: confirm-pledge/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
  changePledge:
    handler: endpoints/changePledge.handler
    events:
      - http:
          method: post
          path: change-pledge/{emailAddress}
          cors: true
          request:
            parameters:
              paths:
                emailAddress: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  sendPledgeDetail:
    handler: endpoints/sendPledgeDetail.handler
    reservedConcurrency: 10
    events:
      - sqs:
          batchSize: 50
          maximumBatchingWindow: 1
          arn:
            Fn::GetAtt:
              - SendPledgeDetailQueue
              - Arn
  downloadFile:
    handler: endpoints/downloadFile.handler
    timeout: 30
    events:
      - http:
          method: post
          path: download-file
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.userPools.${self:custom.stage}}
resources:
  - ${file(../resources/send-pledge-sqs-queue.yml)}
  - ${file(../resources/api-gateway-responses.yml)}
