service: causef-api-v2-reports

frameworkVersion: "4"

plugins:
  - serverless-domain-manager
custom:
  environment: ${file(../.env.${sls:stage}.yml)}
  customDomain:
    domainName: ${self:custom.environment.CUSTOM_DOMAIN}
    basePath: reports
    stage: ${sls:stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs14.x
  profile: jamiebuckell
  stage: ${sls:stage}
  region: ${self:custom.environment.AWS_ACCOUNT_REGION}
  environment: ${file(../.env.${sls:stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.SUBSCRIBERS_TABLE}
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  dropOffs:
    handler: endpoints/dropOffs.handler
    events:
      - http:
          method: get
          path: drop-offs/{campaignId}/{date}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
                date: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  allDropOffs:
    handler: endpoints/allDropOffs.handler
    events:
      - http:
          method: get
          path: all-drop-offs/{campaignId}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    timeout: 30
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
resources:
  - ${file(../resources/api-gateway-responses.yml)}
