service: causef-api-v2-nominators

frameworkVersion: "3"

plugins:
  - serverless-domain-manager
custom:
  environment: ${file(../.env.${sls:stage}.yml)}
  customDomain:
    domainName: ${self:custom.environment.CUSTOM_DOMAIN}
    basePath: nominators
    stage: ${sls:stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${sls:stage}
  region: ${self:custom.environment.AWS_ACCOUNT_REGION}
  environment: ${file(../.env.${sls:stage}.yml)}
  apiGateway:
    description: Microservice for organisation specific processes
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendRawEmail"
      Resource:
        - arn:aws:ses:eu-west-1:988218197909:identity/jamiebuckell.co.uk
        - arn:aws:ses:eu-west-1:988218197909:identity/cause-foundation.org.uk
        - arn:aws:ses:eu-west-1:988218197909:configuration-set/cause-failure-configuration
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.EMAIL_TEMPLATES_TABLE}
    - Effect: "Allow"
      Action:
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:ListUsersInGroup
        - cognito-idp:ListUsers
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:cognito-idp:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":userpool/"
              - ${self:custom.environment.USER_POOL}
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  create:
    handler: endpoints/create.handler
    events:
      - http:
          method: post
          path: create
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  register:
    handler: endpoints/create.handler
    events:
      - http:
          method: post
          path: register
          cors: true
          integration: lambda-proxy
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  sendWelcome:
    handler: endpoints/sendWelcome.handler
    events:
      - http:
          method: post
          path: send-welcome/{userId}
          cors: true
          request:
            parameters:
              paths:
                userId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  approve:
    handler: endpoints/approve.handler
    events:
      - http:
          method: post
          path: approve/{nominatorId}/{organisationId}
          cors: true
          request:
            parameters:
              paths:
                nominatorId: true
                organisationId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  resetPassword:
    handler: endpoints/resetPassword.handler
    events:
      - http:
          method: post
          path: reset-password/{nominatorId}
          cors: true
          request:
            parameters:
              paths:
                nominatorId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
  update:
    handler: endpoints/update.handler
    events:
      - http:
          method: post
          path: update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
resources:
  - ${file(../resources/api-gateway-responses.yml)}
