Resources:
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.FEEDBACK_TABLE}
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      BillingMode: PROVISIONED