Resources:
  MailerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.environment.MAILER_QUEUE}
      VisibilityTimeout: 300
      FifoQueue: true
      ContentBasedDeduplication: true
