service: causef-api-v2-feedback

frameworkVersion: "4"

plugins:
  - serverless-domain-manager
custom:
  environment: ${file(../.env.${sls:stage}.yml)}
  customDomain:
    domainName: ${self:custom.environment.CUSTOM_DOMAIN}
    basePath: feedback
    stage: ${sls:stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs16.x
  profile: jamiebuckell
  stage: ${sls:stage}
  region: ${self:custom.environment.AWS_ACCOUNT_REGION}
  environment: ${file(../.env.${sls:stage}.yml)}
  apiGateway:
    description: Microservice for feedback specific processes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI1"
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
        - "Fn::GetAtt": [FeedbackTable, Arn]
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/cause-campaign-feedback-live"
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:eu-west-2:988218197909:function:PdfGeneratorV2Stack-HtmlToPdfLambdaB7443488-LJXTgl6nvBE2
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  volunteer:
    handler: endpoints/volunteer.handler
    events:
      - http:
          method: post
          path: volunteer
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  hamper:
    handler: endpoints/hamper.handler
    events:
      - http:
          method: post
          path: hamper
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  hamperCheck:
    handler: endpoints/hamperCheck.handler
    events:
      - http:
          method: post
          path: hampers/check
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  getHamper:
    handler: endpoints/getHamper.handler
    events:
      - http:
          method: get
          path: hampers/list/{campaignId}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
  getVolunteer:
    handler: endpoints/getVolunteer.handler
    events:
      - http:
          method: get
          path: volunteers/list/{campaignId}
          cors: true
          request:
            parameters:
              paths:
                campaignId: true
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
  generatePdf:
    handler: endpoints/generatePdf.handler
    events:
      - http:
          method: post
          path: hampers/generate
          cors: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
  transfer:
    handler: endpoints/transfer.handler
    timeout: 180
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:uuid:1
resources:
  - ${file(../resources/feedback-table.yml)}
  - ${file(../resources/api-gateway-responses.yml)}
