service: causef-api-v2-organisations

frameworkVersion: "4"

plugins:
  - serverless-domain-manager
custom:
  environment: ${file(../.env.${sls:stage}.yml)}
  customDomain:
    domainName: ${self:custom.environment.CUSTOM_DOMAIN}
    basePath: organisations
    stage: ${sls:stage}
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs14.x
  profile: jamiebuckell
  stage: ${sls:stage}
  region: ${self:custom.environment.AWS_ACCOUNT_REGION}
  environment: ${file(../.env.${sls:stage}.yml)}
  apiGateway:
    description: Microservice for organisation specific processes
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendRawEmail"
      Resource:
        - arn:aws:ses:eu-west-1:988218197909:identity/jamiebuckell.co.uk
        - arn:aws:ses:eu-west-1:988218197909:identity/cause-foundation.org.uk
        - arn:aws:ses:eu-west-1:988218197909:configuration-set/cause-failure-configuration
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:eu-west-2:"
              - ${self:custom.environment.AWS_ACCOUNT_ID}
              - ":table/"
              - ${self:custom.environment.MAIN_DYNAMO_TABLE}
              - "/index/GSI2"
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - ../common/**
    - endpoints/**
functions:
  create:
    handler: endpoints/create.handler
    events:
      - http:
          method: post
          path: create
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  update:
    handler: endpoints/update.handler
    events:
      - http:
          method: post
          path: update
          cors: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:nanoid:2
  delete:
    handler: endpoints/delete.handler
    events:
      - http:
          method: post
          path: delete/{organisationId}
          cors: true
          request:
            parameters:
              paths:
                organisationId: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
  checkReference:
    handler: endpoints/checkReference.handler
    events:
      - http:
          method: post
          path: check-reference/{reference}
          cors: true
          request:
            parameters:
              paths:
                reference: true
          integration: lambda-proxy
          authorizer:
            name: PrivateAuthorizerV2
            type: COGNITO_USER_POOLS
            arn: ${self:custom.environment.USER_POOL_ARN}
  getByHash:
    handler: endpoints/getByHash.handler
    events:
      - http:
          method: get
          path: get-by-hash/{organisationId}/{hash}
          cors: true
          request:
            parameters:
              paths:
                organisationId: true
                hash: true
    layers:
      - arn:aws:lambda:eu-west-2:988218197909:layer:moment:1
      - arn:aws:lambda:eu-west-2:988218197909:layer:crypto:1
resources:
  - ${file(../resources/api-gateway-responses.yml)}
